services:
  frontend:
    build: ./reservations_frontend
    volumes:
      - ./reservations_frontend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev

  backend:
    build:
      context: ./reservations_backend
      dockerfile: Dockerfile.dev
    container_name: nest-backend
    ports:
      - "4000:3000" # NestJS app runs on 3000 inside container, exposed as 4000 locally
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_NAME=reservations
      - JWT_SECRET=tajna123
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - postgres
    volumes:
      - ./reservations_backend/src:/app/src
      - ./reservations_backend/node_modules:/app/node_modules
    command: npm run start:dev

  postgres:
    image: postgres:17
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: reservations
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata:
