version: "3.9"

services:
  backend:
    build:
      context: ./reservations_backend
      dockerfile: Dockerfile.prod
    container_name: nest-backend-prod
    ports:
      - "4000:3000"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_NAME=reservations
      - JWT_SECRET=tajna123
      - NODE_ENV=production
    depends_on:
      - postgres

  postgres:
    image: postgres:17
    container_name: postgres-db
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=reservations
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata:

