version: "3.8"

services:
  frontend:
    build: ./reservations_frontend
    ports:
      - "3000:80"  # Frontend available at localhost:3000
    depends_on:
      - backend

  backend:
    build: ./reservations_backend
    container_name: nest-backend
    ports:
      - "4000:3000"  # NestJS app runs on 3000 inside container, exposed as 4000 locally
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_NAME=reservations
      - JWT_SECRET=tajna123
      - NODE_ENV=development
    depends_on:
      - postgres
    volumes:
      - ./reservations_backend:/app
      - /app/node_modules
    command: npm run start:dev

  postgres:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: reservations
    ports:
      - "5432:5432"
    volumes:
      - reservations-backend_pgdata:/var/lib/postgresql/data

volumes:
  reservations-backend_pgdata:
            external: true
